### ISSUE TITLE
Health Check Endpoint

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#1]
# Priority: HIGH
Implement Health Check Endpoint:
This will be called to check the status of the API.

**Comment by syntrydy** [comment]
Implemented:
1. /health
`
{
    "status": "UP",
    "checks": [
        {
            "name": "oxauth-config-api liveness",
            "status": "UP"
        },
        {
            "name": "oxauth-config-api readiness",
            "status": "UP"
        }
    ]
}
`
1. /health/live
`
{
    "status": "UP",
    "checks": [
        {
            "name": "oxauth-config-api liveness",
            "status": "UP"
        }
    ]
}
`
1. /health/ready
`
{
    "status": "UP",
    "checks": [
        {
            "name": "oxauth-config-api readiness",
            "status": "UP"
        }
    ]
}
`

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/86332057-91ae6400-bc67-11ea-9d6c-3f16907b3c04.png)
