### ISSUE TITLE
Dynamic client registration configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#10]
# Description
This endpoint should be used to configure dynamic registration settings.
# Endpoint
    https://servername/api/v1/oxauth/dyn_registration
# Supported methods
   1. **GET**: retrieve dynamic registration settings.
   1. **PUT**: update dynamic registration settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - dynamicRegistrationEnabled
   - dynamicRegistrationPasswordGrantTypeEnabled
   - dynamicRegistrationExpirationTime
   - dynamicRegistrationPersistClientAuthorizations
   - dynamicRegistrationScopesParamEnabled
   - dynamicRegistrationCustomObjectClass
   - legacyDynamicRegistrationScopeParam
   - dynamicGrantTypeDefault
   - defaultSubjectType
   - dynamicRegistrationCustomAttributes

**Comment by pujavs** [comment]
Implemented /api/v1/oxauth/dyn_registration
{"defaultSubjectType":"pairwise",
"dynamicGrantTypeDefault":["refresh_token","implicit","client_credentials","authorization_code","urn:ietf:params:oauth:grant-type:uma-ticket"],
"dynamicRegistrationCustomAttributes":["oxAuthTrustedClient"],
"dynamicRegistrationCustomObjectClass":""
,"dynamicRegistrationEnabled":true,
"dynamicRegistrationExpirationTime":-1,
"dynamicRegistrationPasswordGrantTypeEnabled":false,
"dynamicRegistrationPersistClientAuthorizations":true,
"dynamicRegistrationScopesParamEnabled":true,"
legacyDynamicRegistrationScopeParam":false}

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/89658856-ac21d000-d8ec-11ea-99e5-17cd9572b8c9.png)
