### ISSUE TITLE
Provide endpoint on oxtrust-api to create trust relationship

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#101]
## Describe the issue
Customers want to create trust relationships objects using oxtrust-api.

- Should provide an endpoint to create a Trust relationship
- Should provide an endpoint to update a Trust relationship
- Should provide endpoints to attach metadata to trust relationship

**Comment by yuriyz** [comment]
> Mike: `none of the SAML stuff will be moved.`

Closing since TR functionality will not be part of foundation.
