### ISSUE TITLE
API Consumer updates an OpenID scope

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#103]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can update an existing OpenID scope
given it's `inum`

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/v1/oauth/scopes/{inum}` where `{inum}` is the inum of an existing 
    OpenID scope
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains a representation of the OpenID scope to update
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the updated OpenID scope

#### Notes 
   No notes

**Comment by syntrydy** [comment]
Fixed
