### ISSUE TITLE
API Consumer partially updates an OpenID scope

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#105]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that  partially updates an OpenID scope
given it's `{inum}`

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/openid/scopes/{inum}`** where `{inum}` is the inum of an existing 
   OpenID scope
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains a partial representation of the OpenID scope to update
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the updated OpenID scope

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92252746-90e3b980-eec6-11ea-9993-abd872f576f4.png)
