### ISSUE TITLE
API Consumer partially updates a non-existing OpenID scope

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#106]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that partially updates  non-existing OpenID scope
so that I can get an error describing why the operation failed.

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/openid/scopes/{inum}`** where `{inum}` is the inum of a non-existing 
   OpenID scope
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains a partial representation of the OpenID scope to partially update
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed
#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92272944-669ff500-eee2-11ea-9af9-807208eccee1.png)
