### ISSUE TITLE
API Consumer deletes an OpenID Scope

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#107]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can delete an existing 
OpenID scope given it's `inum`

#### Acceptance Criteria 
- `API Consumer` sends a `DELETE` request to `/api/v1/openid/scopes/{inum}` where `{inum}` is the inum of an existing 
   OpenID scope
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the updated list of OpenID scopes

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89185822-c1b49400-d592-11ea-9257-da51e34770b2.png)
