### ISSUE TITLE
Client Claim Management

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxauth-config#109]
Use case from Customer:

```
We need to be able to add custom attributes to the client config. I know we can add custom person attributes to the but looking in the UI, I’m not seeing a way to add custom client attributes.
```

Of course for LDAP, these client claims would need to first be added to the LDAP schema (this is out of scope of oxauth-config)... so we assume the database can handle these claims.

But we need client claim CRUD... list, add, update, delete, modify.

**Comment by pujavs** [comment]
**Client Claim :**  Client claim is additional information about a client. Example of a claim would be "email": "puja.sharms@example.com".
Claims are defined as name/value pairs.

**Requirement:** Client Claim Management Resource will enable to define and manage custom client attributes.

**Proposed Change:**
_oxAuth:_ 
1) /oxauth-common/src/main/java/org/gluu/oxauth/model/registration/Client.java
Based on the understanding that existing property  private List<CustomAttribute> customAttributes cannot be used
Define new property and getter setter.
@AttributeName(name = "oxCustomClaim")
@AttributesList(name = "name", value = "values", sortByName = true)
private  List<CustomAttribute> customClaims; (will use org.gluu.persist.model.base.CustomAttribute)

2)/oxauth-server/src/main/java/org/gluu/oxauth/service/ClientService.java
Define new method getCustomClaims() and setCustomClaims()

_oxauth-config:_
We have an existing org.gluu.configapi.rest.resource.ClientsResource. This can hendle the clientclaims as is.
Do we need a sperate methods for clientClaims or a new resource to handle only clientClaims?

**Comment by yuriyz** [comment]
1. See setter `org.gluu.oxauth.model.registration.Client#setCustomAttributes`
2. I guess we can reuse existing HTTP methods. E.g. it should be possible POST new client with custom attributes. As well as PATCH it. Same for GET.

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/93875125-0c7c9d80-fcf2-11ea-8711-df17266d8c19.png)

**Comment by pujavs** [comment]
[Uploading openid.clients.custom-attribute.pdf…]()

**Comment by pujavs** [comment]
**  Prerequisite details**
Modify LDAP schema to define new attribute for objectClasses oxAuthClient
Refer https://gluu.org/docs/gluu-server/4.0/admin-guide/attribute/#custom-attributes for the same.
