### ISSUE TITLE
Session Id configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#11]
# Description
This endpoint should be used to configure session id settings.
# Endpoint
    https://servername/api/v1/oxauth/sessionid
# Supported methods
   1. **GET**: retrieve session id config settings.
   1. **PUT**: update session id config settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - sessionIdUnusedLifetime
   - sessionIdUnauthenticatedUnusedLifetime
   - sessionIdLifetime
   - sessionIdEnabled
   - changeSessionIdOnAuthentication
   - sessionIdRequestParameterEnabled
   - sessionIdPersistOnPromptNone
   - serverSessionIdLifetime

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90086906-24e3ba80-dd39-11ea-9dae-242e27f24f52.png)
