### ISSUE TITLE
API Consumer fetches all person authentication scripts

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#110]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can fetch all person authentication scripts
filtered by an optional set of parameters
- `pattern`: This query parameter specifies a search pattern used to filter the entries by it's searchable attributes
- `limit`: This query parameter allows the `API Consumer` to limit the size of result

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/v1/scripts/person_authn`
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- The request may contain query filter parameters
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a list of person authentication scripts, which can be empty

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89887697-a9fa9280-dbc6-11ea-8406-a9cbd75131fe.png)
