### ISSUE TITLE
Metrics configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#12]
# Description
This endpoint should be used to configure oxauth metrics.
# Endpoint
    https://servername/api/v1/oxauth/metrics
# Supported methods
   1. **GET**: retrieve oxauth metrics settings.
   1. **PUT**: update oxauth metrics settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   1. metricReporterEnabled
   1. metricReporterKeepDataDays
   1. metricReporterInterval

**Comment by pujavs** [comment]
**Details:** Metrics endpoint enables to retrieve and update metrics configure related to gathering metrics statistics for authentication-related events generated by Gluu Gateway against its associated Gluu Server.

**Configuration Attributes:**
⋅⋅*metricReporterInterval : The interval for metric reporter in seconds.
⋅⋅*metricReporterKeepDataDays: The days to keep metric reported data.
⋅⋅*metricReporterEnabled:  Boolean value specifying whether to enable Metric Reporter.

**Comment by pujavs** [comment]
![oxauth-config_issues_12_testing](https://user-images.githubusercontent.com/43700552/83264132-496dd300-a1dd-11ea-80fe-f9e8fd603ba3.JPG)

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/89659149-15a1de80-d8ed-11ea-9a77-f77feb9bef71.png)
