### ISSUE TITLE
Pairwise configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#13]
# Description
This endpoint should be used to configure pairwise settings.
# Endpoint
    https://servername/api/v1/oxauth/pairwise
# Supported methods
   1. **GET**: retrieve pairwise settings.
   1. **PUT**: update pairwise settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - pairwiseIdType
   - pairwiseCalculationKey
   - pairwiseCalculationSalt

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/89548988-60f0ba00-d825-11ea-8ec4-cb7ff204a0fd.png)
