### ISSUE TITLE
Configuration – Authentication Protection Configuration

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#131]
# Priority: HIGH
# Description
This endpoint should be used for oxAuth authentication protection configuration settings.
# Endpoint
https://<servername:port>/api/v1/oxauth/config/properties/auth-protection
# Supported methods
   1. **GET**: retrieve oxAuth authentication protection configuration settings. API consumer must have **read** permission to access this endpoint.
   1. **PUT**: update oxAuth authentication protection configuration settings. API consumer must have **write** permission to access this endpoint.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by yuriyz** [comment]
It's covered by oxauth config PATCH.
