### ISSUE TITLE
Graphics - Logo

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#132]
# Priority: LOW
# Description
This endpoint should be used for logo graphics configuration settings.
# Endpoint
https://<servername:port>/api/v1/oxauth/config/graphics/logo
# Supported methods
   1. **GET**: retrieve oxAuth logo graphics configuration settings. API consumer must have **read** permission to access this endpoint.
   2. **POST**: update oxAuth logo graphics configuration settings. API consumer must have **write** permission to access this endpoint.
   3. **PUT**: update oxAuth logo graphics configuration settings. API consumer must have **write** permission to access this endpoint.
   4. **DELETE**: update oxAuth logo graphics configuration settings. API consumer must have **write** permission to access this endpoint.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by syntrydy** [comment]
Path operation can be used for this
