### ISSUE TITLE
Graphics - Favicon

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#133]
# Priority: LOW
# Description
This endpoint should be used for favicon graphic configuration settings.
# Endpoint
https://<servername:port>/api/v1/oxauth/config/graphics/favicon 
# Supported methods
   1. **GET**: retrieve favicon graphic configuration settings. API consumer must have **read** permission to access this endpoint.
   2. **POST**: add new favicon graphic configuration settings. API consumer must have **write** permission to access this endpoint.
   3. **PUT**: update favicon graphic configuration settings. API consumer must have **write** permission to access this endpoint.
   4. **DELETE**: delete favicon graphic configuration settings. API consumer must have **write** permission to access this endpoint.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by yuriyz** [comment]
Currently favicon is references in oxauth as
`<link rel="icon" href="#{oxAuthConfigurationService.getImgLocation()}/<file name on disk>" />`

`imgLocation` can be modified by config PATCH. So nothing to do within this ticket.
