### ISSUE TITLE
Database - Couchbase configuration : API for handling Couchbase configuration

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#136]
# Priority: HIGH
# Description
Database - Couchbase configuration :- API for Couchbase configuration
# Endpoint
https://<servername:port>/api/v1/oxauth/config/database/couchbase 
# Supported methods
   1. **GET**: retrieves existing Couchbase configuration. API consumer must have **read** permission to access this endpoint.
   2. **POST**: adds new Couchbase configuration. API consumer must have **write** permission to access this endpoint.
   3. **PUT**: full update of existing Couchbase configuration. API consumer must have **write** permission to access this endpoint.
   4. **PATCH**: partial update of existing Couchbase configuration. API consumer must have **write** permission to access this endpoint.
   5. **DELETE**: deletes new Couchbase configuration. API consumer must have **write** permission to access this endpoint.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by yuriyz** [comment]
Implemented.
