### ISSUE TITLE
Fido2 configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#14]
# Description
This endpoint should be used to configure fido2 settings.
# Endpoint
    https://servername/api/v1/oxauth/fido2
# Supported methods
   1. **GET**: retrieve fido2 settings.
   1. **PUT**: update fido2 settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - authenticatorCertsFolder
   - mdsAccessToken
   - mdsCertsFolder
   - mdsTocsFolder
   - userAutoEnrollment
   - unfinishedRequestExpiration
   - authenticationHistoryExpiration
   - serverMetadataFolder
   - disableFido2

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/89906716-5cebe000-dc09-11ea-9b49-50c9052e6ceb.png)

**Comment by pujavs** [comment]
disableFido2 property not found in config. Shall we move it to General Server config endpoint

**Comment by pujavs** [comment]
[Fido2.Test_Report.pdf](https://github.com/GluuFederation/oxauth-config/files/5275453/Fido2.Test_Report.pdf)
