### ISSUE TITLE
Custom Scripts - Consent Gathering - Create new script

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#141]
# Priority: MEDIUM
# Description
This generic endpoint to create new consent gathering custom scripts.
# Endpoint
https://<servername:port>/api/v1/oxauth/scripts/consent
# Supported methods
   1. **POST**: Add a new custom scripts by type. API consumer must have **write** permission to access this endpoint.
   # Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by syntrydy** [comment]
Done here https://github.com/GluuFederation/oxauth-config/issues/140
