### ISSUE TITLE
Configuration – SMTP: API for handling SMTP server configuration.

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#147]
# Priority: HIGH
# Description
This endpoint should be used to for fetching and setting SMTP server cache configuration.
# Endpoint
https://<servername:port>/api/v1/oxauth/config/cache/smtp
# Supported methods
   1. **GET**: Retrieves SMTP server cache configuration. API consumer must have **read** permission to access this endpoint.
   1. **POST**: Add a SMTP server cache configuration. API consumer must have **write** permission to access this endpoint.
   1. **PUT**: Update an SMTP server cache configuration. API consumer must have **write** permission to access this endpoint.
   1. **PUT**: Delete an SMTP server cache configuration. API consumer must have **write** permission to access this endpoint.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/91225428-859ccb00-e71b-11ea-963f-4ce143acdfc1.png)

**Comment by syntrydy** [comment]
Done, all test passing
