### ISSUE TITLE
Configuration – JWK - JSON Web Key (JWK): API for general JWK operations.

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#149]
# Priority: HIGH
# Description
This endpoint can be used to view existing JWK as well as add new JWK.
# Endpoint
https://<servername:port>/api/v1/oxauth/config/jwks
# Supported methods
   1. **GET**:  Retrieves list of JSON Web Key (JWK) used by server. API consumer must have **read** permission to access this endpoint.
   1. **PUT**: Adds a new JSON Web Key (JWK). API consumer must have **write** permission to access this endpoint.
   # Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by yuriyz** [comment]
Added support to GET, PUT and PATCH JWKS. Thus removed individual key operations (since it's covered by PATCH).
