### ISSUE TITLE
CIBA configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#15]
# Description
This endpoint should be used to configure CIBA settings.
# Endpoint
    https://servername/api/v1/oxauth/ciba
# Supported methods
   1. **GET**: retrieve CIBA settings.
   1. **PUT**: update CIBA settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - apiKey
   - authDomain
   - databaseURL
   - projectId
   - storageBucket
   - messagingSenderId
   - appId
   - notificationUrl
   - notificationKey
   - publicVapidKey

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90009382-8f561580-dcbb-11ea-871f-a7b5fceaf3d8.png)

**Comment by pujavs** [comment]
Have added two more parameters **cibaGrantLifeExtraTimeSec** and **cibaMaxExpirationTimeAllowedSec**
