### ISSUE TITLE
Configuration – JWK - JSON Web Key (JWK): API for JWK operations based on key ID.

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#150]
# Priority: HIGH
# Description
This endpoint can be used to view, partially update, complete update as well as deletion of a specific JWK.
# Endpoint
https://<servername:port>/api/v1/oxauth/config/jwks/{id}
# Supported methods
   1. **GET**: Gets the specified JSON Web Key (JWK). API consumer must have **read** permission to access this endpoint.
   1. **PUT**: Updates all fields of the specified JSON Web Key (JWK). API consumer must have **write** permission to access this endpoint.
   1. **PATCH**: Updates only modified fields of the specified JSON Web Key (JWK). API consumer must have **write** permission to access this endpoint.
    # Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by yuriyz** [comment]
Implemented.
