### ISSUE TITLE
OAuth - UMA Resources: API Consumer for create and update an UMA Resources.

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#151]
# Priority: MEDIUM
# Description
This endpoint can be used to create a new UMA Resources.
# Endpoint
https://<servername:port>/api/v1/oxauth/uma/resources
# Supported methods
   1. **POST**: Creates an UMA resource. API consumer must have **write** permission to access this endpoint.
   1. **PUT**: Updates an UMA resource. API consumer must have **write** permission to access this endpoint.
   # Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by syntrydy** [comment]
Duplicate with :
- https://github.com/GluuFederation/oxauth-config/issues/64
- https://github.com/GluuFederation/oxauth-config/issues/57
- https://github.com/GluuFederation/oxauth-config/issues/59
- https://github.com/GluuFederation/oxauth-config/issues/60
