### ISSUE TITLE
Configuration – Properties: Fetch all oxAuth configuration properties.

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#152]
# Priority: HIGH
# Description
This endpoint can be used to fetch all oxAuth configuration properties.
# Endpoint
https://<servername:port>/api/v1/oxauth/config/properties
# Supported methods
   1. **GET**: Gets all oxAuth configuration properties. API consumer must have **read** permission to access this endpoint.
   # Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.
# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml

**Comment by yuriyz** [comment]
Outdated and works already.
