### ISSUE TITLE
API Consumer adds a new OpenID scopes to an existing OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#153]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can add an OpenID scope to an existing 
OpenID client

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/oxauth/openid/clients/{inum}/scopes` where `{inum}` is the inum of 
   an existing OpenID client
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains data of the format 
   ```
   {
     "scopes" : ["scope_inum_1","scope_inum_2",...] 
   }
   ```
   Where `scope_inum_n` is a scope to add to the OpenID client
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a the result of the operation for each scope in the format below. 
  200 means the OpenID scope was added , 404 means the OpenID scope was not found (attempting to add a non-existing scope)
   ```
     {
       "scope_inum_1": 200,
       "scope_inum_2": 404,
     }
   ```

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/91212612-5af54700-e708-11ea-9776-669b461880e8.png)

**Comment by syntrydy** [comment]
@uprightech do we have this in swagger spec already?
