### ISSUE TITLE
API Consumer adds a new OpenID scope to non-existing OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#154]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that adds an OpenID scope to a non-existing 
OpenID client so that I can get an error describing why the operation failed.

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/oxauth/openid/clients/{inum}/scopes` where `{inum}` is the inum of 
   a non-existing OpenID client
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains data of the format 
   ```
   {
     "scopes" : ["scope_inum_1","scope_inum_2",...] 
   }
   ```
   Where `scope_inum_n` is a scope to add to the OpenID client
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/91212612-5af54700-e708-11ea-9776-669b461880e8.png)
