### ISSUE TITLE
API Consumer removes an OpenID scope from an OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#155]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can delete an OpenID scope associated to an existing
OpenID client.

#### Acceptance Criteria 
- `API Consumer` sends a `DELETE` request to `/api/v1/oxauth/openid/clients/{inum}/scopes/{scope_inum}` where 
   `{inum}` is the inum of the OpenID client and `{scope_inum}` is the inum of the scope to be deleted.
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- The scope must not exist, and should not generate an error if it doesn't.
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a list of scopes associated to the OpenID client

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/91352547-e7276d00-e7e1-11ea-88cc-e468a3e24efc.png)
