### ISSUE TITLE
API Consumer adds a grant type to an OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#157]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can add a grant type to an existing 
OpenID client

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/oxauth/openid/clients/{inum}/grant-types` where `{inum}` is the inum of 
   an existing OpenID client
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains data of the format 
   ```
   {
     "grant-types" : ["grant_type_name_1","grant_type_name_2",...] 
   }
   ```
   Where `grant_type_name_n` is the name of a grant_type to add to the openid client
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a the result of the operation for each grant type in the format below. 
  200 means the grant type was added , 404 means the grant type was not found (attempting to add a non-existing grant type)
   ```
     {
       "grant_type_1": 200,
       "grant_type_2": 404,
     }
   ```

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/91436149-6eff8c80-e85f-11ea-88f1-4011e0edc430.png)
