### ISSUE TITLE
Introduce generic PATCH operation support (rfc6902) to reduce number of endpoint (and as result future maintenance).

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxauth-config#158]
### PATCH 

We have configuration objects which are changing very frequently during development:

- oxauth configuration 
- client configuration

Currently we hit the path when properties of these objects are grouped and looks RESTy but has following disadvantages:

- introducing new endpoints (with all related classes)
- on changes in `oxauth` project we will be forced to always return back and reflect changes in `oxauth-config` project.

Idea is to support [RFC 6902](https://tools.ietf.org/html/rfc6902) . It should allow to avoid both: new endpoints and manual changes reflection.

There is lib on java which has full support of this rfc thus it should be easy for us to apply it.

Note that content type must be `application/json-patch+json`.

Sample from spec:

```
  PATCH /my/data HTTP/1.1
   Host: example.org
   Content-Length: 326
   Content-Type: application/json-patch+json
   If-Match: "abc123"

   [
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
     { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
   ]
```

## Endpoint
https://servername:port/api/v1/oxauth/config/properties

## Acceptance Criteria
We need test for each primitive and complex type inside configuration object
- int
- string
- Boolean
- `List<String>`
- `List<AuthenticationFilter>`
...

**Comment by pujavs** [comment]
Changes done by Yuriy Zabrovarnyy 
Following are important implementation details:
1) Used application/json-patch+json
2) Replaced quarkus-resteasy-jackson instead of quarkus-resteasy-jsonb RESTEasy lib
3) ResteasyContextParameters.RESTEASY_PATCH_FILTER_DISABLED set to true as this is disabled by default.
