### ISSUE TITLE
Introduce global exception handler to avoid boilerplate try/catch in code

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxauth-config#160]
### Each service method is wrapped by try/catch boilerplate code.

Currently there in each REST method we have try/catch which catching all exceptions and returns internal server error. We can avoid such code in each method by providing global exception handler.

Example:
```
	@POST
	@ProtectedApi(scopes = { WRITE_ACCESS })
	public Response setupSmtpConfiguration(@Valid @NotNull SmtpConfiguration smtpConfiguration) {
		try {
			String password = smtpConfiguration.getPassword();
			if (password != null && !password.isEmpty()) {
				smtpConfiguration.setPassword(encryptionService.encrypt(password));
				password = null;
			}
			GluuConfiguration configurationUpdate = configurationService.getConfiguration();
			configurationUpdate.setSmtpConfiguration(smtpConfiguration);
			configurationService.updateConfiguration(configurationUpdate);
			return Response.status(Response.Status.CREATED)
					.entity(configurationService.getConfiguration().getSmtpConfiguration()).build();
		} catch (Exception e) {
			return getInternalServerError(e);
		}
	}

```

Reference: https://github.com/quarkusio/quarkus/issues/2217#issuecomment-486912606

**Comment by syntrydy** [comment]
@yuriyz i think it is okay for this task. Will merge it is master after some verifications.

**Comment by yuriyz** [comment]
Two notes: 
1) we should handle `WebApplicationException` properly which is main way how response can be delivered from any level of depth (especially during validation)
2) ErrorResponse (with factory/builder) wrapped by `WebApplicationException` looks more strightforward (then separate `ApiException`).

**Comment by yuriyz** [comment]
Otherwise good work, no this try/catch all over the resource methods.

**Comment by syntrydy** [comment]
Rework done

**Comment by yuriyz** [comment]
Looks good, I guess we can consider this ticket as done.
