### ISSUE TITLE
OAuth - UMA Scopes 

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/oxauth-config#169]
# Description
This endpoint can be used to create, view, add, search, partially update, complete update as well as deletion of a UMA scope.
# Endpoint
https://<servername:port>/api/v1/oxauth/uma/scopes/{inum} 
# Supported methods
   1. **GET**: Gets all UMA scope or optional can search for UMA scopes based on pattern.
   2. **GET/{id}**: Gets an UMA scope based on unique identifier.
   3. **POST**: Create a new UMA scope
   4. **PUT**: Updates an existing UMA scope
   5. **PATCH**: Patches an existing UMA scope
   6. **DELETE**: Deletes an UMA scope.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Acceptance Criteria
- API should handle error scenarios and throw appropriate exception.
- The API consumer must have required permission to access the endpoint.
- Operation should be successful.

# Swagger Spec
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxauth-config/master/docs/oxauth-config-swagger.yaml#/OAuth_-_UMA_Scopes
____

**Comment by yuriyz** [comment]
OAuth/Connect and UMA scopes are the same since UMA2. Regular scope endpoint already provides CRUD for UMA scopes. It doesn't make sense to create duplicated endpoint. (see `org.gluu.oxauth.model.common.ScopeType`)
