### ISSUE TITLE
oxauth cors configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#17]
# Description
This endpoint should be used to cors settings.
# Endpoint
    https://servername/api/v1/oxauth/cors
# Supported methods
   1. **GET**: retrieve cors settings.
   1. **PUT**: update cors settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
     - Cors Configuration Filters(a list of cors filters)

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90133504-3a82cf80-dd8d-11ea-9dee-37e457fc07d8.png)
