### ISSUE TITLE
oxauth available endpoints configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#18]
# Description
This endpoint should be used to oxauth available endpoints.
# Endpoint
    https://servername/api/v1/oxauth/endpoints
# Supported methods
   1. **GET**: retrieve oxauth available endpoints.
   1. **PUT**: update oxauth available endpoints.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - baseEndpoint
   - authorizationEndpoint
   - tokenEndpoint
   - tokenRevocationEndpoint
   - userInfoEndpoint
   - clientInfoEndpoint
   - endSessionEndpoint
   - registrationEndpoint
   - openIdDiscoveryEndpoint
   - openIdConfigurationEndpoint
   - idGenerationEndpoint
   - introspectionEndpoint
   - umaConfigurationEndpoint
   - sectorIdentifierEndpoint
   - oxElevenGenerateKeyEndpoint
   - backchannelAuthenticationEndpoint
   - backchannelDeviceRegistrationEndpoint

**Comment by pujavs** [comment]
**Note sector identifier is an obscure feature that almost no one uses and hence sectorIdentifierEndpoint is not included.**

![image](https://user-images.githubusercontent.com/43700552/90479352-2dc6f880-e14c-11ea-9b19-6532bbb4a772.png)
