### ISSUE TITLE
oxauth back channel configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#2]
# Description
This endpoint should be used to configure the backchannel settings of the AS.
# Endpoint
    https://servername/api/v1/oxauth/backchannel
# Supported methods
   1. **GET**: retrieve the stored AS backchannel configuration
   1. **PUT**: update the backchannel configuration of the AS.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - backchannelAuthenticationResponseInterval
   - backchannelAuthenticationResponseExpiresIn
   - backchannelBindingMessagePattern
   - backchannelUserCodeParameterSupported
   - backchannelRedirectUri
   - backchannelClientId
   - backchannelLoginHintClaims
   - backchannelAuthenticationRequestSigningAlgValuesSupported
   - backchannelTokenDeliveryModesSupported
   - backchannelDeviceRegistrationEndpoint
   - backchannelAuthenticationEndpoint

**Comment by pujavs** [comment]
Hi, I understand that “back-channel” is used for direct communication between the IDP and SP. In Gluu we have CIBA - Client Initiated Back-channel Authentication. In that case my understanding is each SP would have its own Backchannel configuration’. 
For this requirement that is oxAuth Backchannel configuration’ endpoint.
**GET** - My query is should’nt it return a List of all back-channel configured ? However JsonConfigurationService.getOxauthAppConfiguration() has only one set.
**PUT** - This takes a Backchannel DTO which will have details for single backchannelClientId. And updating JsonConfigurationService.setOxauthAppConfiguration() , again will correspond to single ?
Please confirm

**Comment by pujavs** [comment]
Backchannel configuration consists of :
1) Global oxauth configuration -> references in this class GluuFederation/oxAuth -> org.gluu.oxauth.model.configuration.AppConfiguration.java
2) Client CIBA related configuration -> references in this class GluuFederation/oxAuth -> org.gluu.oxauth.model.registration.Client.java

Implemented this endpoint for Global oxauth configuration

**Comment by pujavs** [comment]
Implemented  /api/v1/oxauth/backchannel 
    {"backchannelAuthenticationRequestSigningAlgValuesSupported":[],"backchannelAuthenticationResponseExpiresIn":0,"backchannelAuthenticationResponseInterval":0,"backchannelTokenDeliveryModesSupported":[]}

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/89658443-3158b500-d8ec-11ea-8801-4d716326a7d5.png)
