### ISSUE TITLE
Health Status Checker gets the health status of oxauth-config

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#25]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As a `Health Status Checker` I want to know the health status of `oxauth-config`  and optionally of 
any of it's dependencies so I can take appropriate action depending on the returned status.

#### Acceptance Criteria 
- A list of internal components and/or dependencies whose health status is critical must be provided 
- Their health status must be exposed through an endpoint either as a form of aggregate (all okay , means the endpoint reports liveness)

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89781429-347dbc00-db0b-11ea-8ae0-747afe98b6da.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89781545-73137680-db0b-11ea-854c-47b2d611e96f.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89781615-93dbcc00-db0b-11ea-80d8-392c48969c18.png)
