### ISSUE TITLE
Telemetry Data Consumer collects telemetry data from oxauth-config

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#26]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As a `Telemetry Data Consumer` I want to collect various telemetry metrics generated by `oxauth-config` so I can integrate them in other use cases such as performance monitoring , chart plotting , etc ... 

#### Acceptance Criteria 
- A (non-exhaustive) list of metrics that can be tracked must be provided 
- An endpoint which allows collection of the data (metrics) must be implemented 
- The endpoint must provide the data in at least one standardized method ( start with openmetrics)
- The endpoint must be protected  
#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/93082702-5083f880-f689-11ea-809e-9819252de6ea.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/93083306-4f070000-f68a-11ea-8cdc-78b7644ad697.png)

**Comment by yuriyz** [comment]
This commit contains significant problem, we have to measure always same call. Not push it with thread1 and then allow to finish it by thread2 which would produce trash instead of real metric.
https://github.com/GluuFederation/oxauth-config/commit/3fb1f7b0cd32ab4ef7811612816e4d27560acdfb

**Comment by syntrydy** [comment]
Fixed
