### ISSUE TITLE
API Consumer sends an API request and a generic error occurs

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#37]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` , with a generic  and/or unrecoverable server 
error preventing the operation to complete occuring , so that I receive an error indicating the request has failed.

#### Acceptance Criteria 
- `API Consumer` sends a `GET` , `POST`, `PUT`, `PATCH` , `DELETE`  http request
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have the required permission to access the endpoint 
- `oxauth-config` returns a `500 Internal Server Error` HTTP Response 
- The HTTP response body contains a description of the error message

#### Notes 
   This issue must be implemented for every API endpoint.

**Comment by yuriyz** [comment]
It's already done. However we provide generic message. We don't want to expose internal of the server. For this we have logs.
