### ISSUE TITLE
oxauth supported response modes configuration 

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#4]
# Description
This endpoint should be used to configure the response modes supported by the AS.
# Endpoint
    https://servername/api/v1/oxauth/responses_modes
# Supported methods
   1. **GET**: retrieve supported response modes.
   1. **PUT**: update supported response modes.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON

**Comment by pujavs** [comment]
Implemented => /api/v1/oxauth/responses_modes
 
 ["QUERY","FRAGMENT","FORM_POST"]

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90086659-90795800-dd38-11ea-8e6a-b22676d221b6.png)
