### ISSUE TITLE
API Consumer partially updates a Gluu attribute

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#41]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can partially update an existing 
Gluu attribute.

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/attributes/{inum}`**
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint 
- The request must contain a partial representation of the Gluu attribute
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the partially modified Gluu attribute.

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92274173-a10a9180-eee4-11ea-8e90-a636d74b09fb.png)
