### ISSUE TITLE
API Consumer partially updates a non-existing Gluu attribute 

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#42]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that updates a non-existing Gluu attribute 
so that I get an error message indicating to me the attribute does not exist

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to **`/api/v1/oxauth/attributes/{inum}`**
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint 
- The request must contain a partial representation of the Gluu attribute resource
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains a description of the error message

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92274596-75d47200-eee5-11ea-845d-1caed301b329.png)
