### ISSUE TITLE
API Consumer fetches UMA resources

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#45]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can get a list of UMA resources filtered by
an optional set of query parameters:
- `pattern` : This query parameter specifies a search pattern used to filter the entries by it's searchable LDAP attributes
- `limit` : This query parameter allows the `API Consumer` to limit the size of result

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/uma/resources`
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- The request may contain query filter parameters
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a list of UMA resources , which can be empty

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89570638-67c7fe80-d81e-11ea-8e5f-55f8ea4d2bf0.png)
