### ISSUE TITLE
API Consumer fetches a single UMA Resource

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#46]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can get a single UMA Resource , given 
it's `inum`

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/uma/resources/{inum}` where `inum` is the UMA resource's `inum`
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- The `inum` must be the `inum` of an existing UMA Resource
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a single UMA Resource 

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89571598-d9547c80-d81f-11ea-9549-698654b768e4.png)
