### ISSUE TITLE
oxEleven configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#5]
# Description
This endpoint should be used to configure JanssenPKCS(oxEleven).
# Endpoint
    https://servername/api/v1/oxauth/janssenpkcs
# Supported methods
   1. **GET**: retrieve JanssenPKCS(oxeleven) settings.
   1. **PUT**: update JanssenPKCS(oxeleven) settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   1. oxElevenGenerateKeyEndpoint
   1. oxElevenSignEndpoint
   1. oxElevenVerifySignatureEndpoint
   1. oxElevenDeleteKeyEndpoint
   1. oxElevenTestModeToken

**Comment by pujavs** [comment]
oxElevenJwksEndpoint is obsolete and hence not added

**Comment by pujavs** [comment]
Implemented /api/v1/oxauth/janssenpkcs
  {"janssenPKCSDeleteKeyEndpoint":"https://pujavs2.infinity.com/oxeleven/rest/oxeleven/deleteKey","janssenPKCSGenerateKeyEndpoint":"https://pujavs2.infinity.com/oxeleven/rest/oxeleven/generateKey","janssenPKCSSignEndpoint":"https://pujavs2.infinity.com/oxeleven/rest/oxeleven/sign","janssenPKCSVerifySignatureEndpoint":"https://pujavs2.infinity.com/oxeleven/rest/oxeleven/verifySignature"}

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/89991656-bef82400-dca1-11ea-9f58-580f35bc9261.png)
