### ISSUE TITLE
API Consumer partially updates a UMA Resource

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#50]
### User Story Meta Information
- Risk Level: 1
- **Priority: MEDIUM**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can partially update an existing UMA resource
given it's `inum`

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/uma/resources/{inum}`** where `{inum}` is the inum of 
   an existing UMA resource
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains a partial representation of the UMA resource
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the modified UMA Resource

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92396046-42c7f380-f11c-11ea-982e-8dde49af987c.png)
