### ISSUE TITLE
API Consumer partially updates a non-existing UMA resource

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#51]
### User Story Meta Information
- Risk Level: 1
- **Priority: MEDIUM**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` which contains the `inum` of a non-existing UMA resource in order to modify it so I can receive an error message indicating the UMA resource was not found

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/uma/resources/{inum}`** where `{inum}` is the inum of 
   a non-existing UMA resource
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains a partial representation of the UMA resource
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92394130-e3b4af80-f118-11ea-8547-8dc655238414.png)
