### ISSUE TITLE
API Consumer creates or (partially) updates a resource with with invalid parameters

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#58]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that creates or (partially) updates a REST resource , so that I can receive an error message when the request contains invalid parameters 

#### Acceptance Criteria 
- `API Consumer` sends a `POST`, `PUT` or `PATCH` request to a REST endpoint
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- `oxauth-config` returns a `400 Bad request` HTTP Response 
- The HTTP response body contains an error describing why the request failed

#### Notes 
   No notes

**Comment by yuriyz** [comment]
It's too generic definition. Each service should validate own parameters and report appropriate error.
