### ISSUE TITLE
User Info configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#6]
# Description
This endpoint should be used to configure user info endpoint.
# Endpoint
    https://servername/api/v1/oxauth/user_info
# Supported methods
   1. **GET**: retrieve user info settings.
   1. **PUT**: update user info settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   1. userInfoSigningAlgValuesSupported
   1. userInfoEncryptionAlgValuesSupported
   1. userInfoEncryptionEncValuesSupported

**Comment by pujavs** [comment]
Implemented -> /api/v1/oxauth/user_info
  {"userInfoEncryptionAlgValuesSupported":["RSA1_5","RSA-OAEP","A128KW","A256KW"],"userInfoEncryptionEncValuesSupported":["A128CBC+HS256","A256CBC+HS512","A128GCM","A256GCM"],"userInfoSigningAlgValuesSupported":["HS256","HS384","HS512","RS256","RS384","RS512","ES256","ES384","ES512"]}

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90086743-c3235080-dd38-11ea-9d3d-dd3f1249ca93.png)
