### ISSUE TITLE
API Consumer partially updates a non-existing UMA scope

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#62]
### User Story Meta Information
- Risk Level: 1
- **Priority: MEDIUM**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that partially updates a non-existing UMA scope 
so that I can get an error message indicating why the request failed.

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/uma/scopes/{inum}`** where `{inum}` is the inum of a non-existing
   UMA scope
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains a partial representation of a UMA scope
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the request failed

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92404672-01d7db00-f12c-11ea-9cd5-77502bacbc43.png)
