### ISSUE TITLE
API Consumer updates a non-existing sector identifier

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#69]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that updates a non-existing sector identifier 
so I can get an error message indicating why the operation failed

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/v1/oauth/openid/sectoridentifiers/{inum}` where `{inum}` is the inum of 
   a non-existing sector identifier 
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request must contain a representation of the sector identifier 
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error message describing why the operation failed

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89312169-d7978700-d66e-11ea-8b1b-dff31950188e.png)
