### ISSUE TITLE
Id Token configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#7]
# Description
This endpoint should be used to configure id token.
# Endpoint
    https://servername/api/v1/oxauth/idtoken
# Supported methods
   1. **GET**: retrieve id token config settings.
   1. **PUT**: update id token config settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   1. idTokenSigningAlgValuesSupported
   1. idTokenEncryptionAlgValuesSupported
   1. idTokenEncryptionEncValuesSupported

**Comment by pujavs** [comment]
Implemented /api/v1/oxauth/idtoken/
    {"idTokenEncryptionAlgValuesSupported":["RSA1_5","RSA-OAEP","A128KW","A256KW"],"idTokenEncryptionEncValuesSupported":["A128CBC+HS256","A256CBC+HS512","A128GCM","A256GCM"],"idTokenSigningAlgValuesSupported":["none","HS256","HS384","HS512","RS256","RS384","RS512","ES256","ES384","ES512"]}

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/89658704-7c72c800-d8ec-11ea-82e2-cbfe444259b2.png)
