### ISSUE TITLE
API Consumer partially updates a sector identifier

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#70]
### User Story Meta Information
- Risk Level: 1
- **Priority: LOW**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can partially update an existing sector 
identifier given it's `inum`

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/openid/sectors/{inum}`** where `{inum}` is the inum 
   of an existing sector identifier 
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains the partial representation of a sector identifier resource
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the modified sector identifier 
#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92408770-67c96000-f136-11ea-9bbb-f097e7f6b3bd.png)
