### ISSUE TITLE
API Consumer partially updates a non-existing sector identifier

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#71]
### User Story Meta Information
- Risk Level: 1
- **Priority: LOW**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that partially updates a non existing 
sector identifier so that I can get an error message indicating why the operation failed.

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/openid/sectors/{inum}`** where `{inum}` is the inum 
   of a non-existing sector identifier 
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains the partial representation of a sector identifier resource
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed
#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/92408826-892a4c00-f136-11ea-9cd1-1dc708e0a283.png)
