### ISSUE TITLE
API Consumer creates a sector identifier

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#74]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can create a new sector identifier

#### Acceptance Criteria 
- `API Consumer` sends a `POST` request to `/v1/oauth/openid/sectoridentifiers`
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- `oxauth-config` returns a `201 Created` HTTP Response 
- The HTTP response body contains the newly created sector identifier
#### Notes 
   No notes

**Comment by syntrydy** [comment]
Red https://github.com/GluuFederation/oxauth-config/commit/896c8625e16078912a849828e5851be2e2a98502
