### ISSUE TITLE
API Consumer fetches a single source backend LDAP server configuration entry

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#76]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can fetch a single source backend LDAP server configuration entry

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/config/cacherefresh/servers/{name}` where `{name}` is the name of an existing source backend LDAP server configuration entry
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a single source LDAP server configuration entry

#### Notes 
   No notes

**Comment by yuriyz** [comment]
Cache Refresh is not an oxAuth feature. Thus it is not part of Config API.
