### ISSUE TITLE
API Consumer fetches a non-existing source backend LDAP server configuration entry

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#77]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that fetches a single non-existing
source backend LDAP server configuration entry so that I can get an error message indicating why the operation failed. 

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/config/cacherefresh/servers/{name}` where `{name}` is the name of 
   a  non-existing source backend LDAP server configuration entry
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed

#### Notes 
   No notes

**Comment by yuriyz** [comment]
Cache Refresh is not an oxAuth feature. Thus it is not part of Config API.
