### ISSUE TITLE
API Consumer updates a source backend LDAP server configuration entry

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#79]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can update an existing source backend LDAP server configuration entry given it's name 

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/config/cacherefresh/servers/{name}` where `{name}` is the name of an existing 
  source server configuration entry
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request body contains a representation of the server configuration entry
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the modified source backend LDAP server configuration entry

#### Notes 
   No notes

**Comment by yuriyz** [comment]
Cache Refresh is not an oxAuth feature. Thus it is not part of Config API.
