### ISSUE TITLE
Request object configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#8]
# Description
This endpoint should be used to configure request object settings.
# Endpoint
    https://servername/api/v1/oxauth/request_object
# Supported methods
   1. **GET**: retrieve user info settings.
   1. **PUT**: update user info settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   1. requestObjectSigningAlgValuesSupported
   1. requestObjectEncryptionAlgValuesSupported
   1. requestObjectEncryptionEncValuesSupported

**Comment by pujavs** [comment]
Implemented /api/v1/oxauth/request_object ->
{"requestObjectEncryptionAlgValuesSupported":["RSA1_5","RSA-OAEP","A128KW","A256KW"],"requestObjectEncryptionEncValuesSupported":["A128CBC+HS256","A256CBC+HS512","A128GCM","A256GCM"],"requestObjectSigningAlgValuesSupported":["none","HS256","HS384","HS512","RS256","RS384","RS512","ES256","ES384","ES512"]}

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90086792-e0f0b580-dd38-11ea-8032-c36d6e419364.png)
