### ISSUE TITLE
API Consumer partially updates a source backend LDAP server entry

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#81]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can partially update an existing source LDAP server configuration entry given it's name 

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to `/api/v1/config/cacherefresh/servers/{name}` where `{name}` is the name of 
   an  existing source backend LDAP server configuration entry
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request body contains a partial representation of the source LDAP server configuration entry
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the updated source backend LDAP server configuration entry

#### Notes 
   No notes

**Comment by yuriyz** [comment]
Cache Refresh is not an oxAuth feature. Thus it is not part of Config API.
