### ISSUE TITLE
API Consumer partially updates a non-existing source backend LDAP server entry

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#82]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that  partially updates a non-existing 
source backend LDAP server configuration entry so that I can get an error describing why the operation failed

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/config/cacherefresh/servers/{name}` where `{name}` is the name of  
  a non-existing source backend LDAP server configuration entry
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request body contains a partial representation of the source backend LDAP configuration entry
- `oxauth-config` returns a `404 Not found` HTTP Response 
- The HTTP response body contains a single source backend LDAP server configuration entry

#### Notes 
   No notes

**Comment by yuriyz** [comment]
Cache Refresh is not an oxAuth feature. Thus it is not part of Config API.
