### ISSUE TITLE
API Consumer fetches the oxAuth default authentication acr

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#85]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can get the default authentication
 acr used by `oxauth`

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/acr/oxauth` 
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the oxAuth default authentication acr

#### Notes 
   No notes

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90254720-d3364f80-de60-11ea-8306-ac4f809cf446.png)
