### ISSUE TITLE
API Consumer updates the oxAuth default authentication acr

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#86]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can get the default authentication
 acr used by `oxauth`

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/acr/oxauth` 
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request body contains the new value for the oxAuth default authentication acr
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the modified oxAuth default authentication acr

#### Notes 
   No notes

**Comment by nynymike** [comment]
Why is this a write operation? Do you want to do add/edit/delete too?

**Comment by uprightech** [comment]
No , just update. Right now , we have two categories of permissions : `read` (for GET operations) and `write` (for POST , PUT , PATCH and DELETE)
operations. 
This falls under the second category. An update will modify (write) data. 
Do you think we should have a separate permission type for configuration ?

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90256883-fe6e6e00-de63-11ea-9bc3-7dad78a10445.png)
