### ISSUE TITLE
API Consumer fetches all OpenID clients

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#87]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can fetch all OpenID client entries
filtered by an optional set of parameters
- `pattern`: This query parameter specifies a search pattern used to filter the entries by it's searchable attributes
- `limit`: This query parameter allows the `API Consumer` to limit the size of result

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/clients`
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- The request may contain query filter parameters
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a list of OpenID clients , which can be empty

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89029543-99c0f880-d326-11ea-8ac5-a700d00a79da.png)

**Comment by syntrydy** [comment]
With limit and pattern
![image](https://user-images.githubusercontent.com/7513418/89029900-40a59480-d327-11ea-885d-1c3175c4a69e.png)
