### ISSUE TITLE
API Consumer fetches a single OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#88]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can fetch a single OpenID client given it's
`inum`

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/clients/{inum}` where `{inum}` is the inum of the OpenID client
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a representation of the OpenID client

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89030841-35536880-d329-11ea-85ec-e4e625bb71e0.png)
