### ISSUE TITLE
API Consumer fetches a non-existing OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#89]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that fetches a single non-existing OpenID client 
given it's `{inum}` so that I can get an error describing why the operation failed.

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/api/v1/clients/{inum}` where `{inum}` is the inum of a non-existing 
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89031179-eeb23e00-d329-11ea-82bf-c99c400d0938.png)
