### ISSUE TITLE
UMA configuration

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxauth-config#9]
# Description
This endpoint should be used to configure uma settings.
# Endpoint
    https://servername/api/v1/oxauth/uma
# Supported methods
   1. **GET**: retrieve uma settings.
   1. **PUT**: update uma settings.
# Data types exchanged
  1. **Consumes**: JSON
  1. **Produces**: JSON 
# Data
   - umaRptLifetime
   - userInfoEncryptionAlgValuesSupported
   - umaTicketLifetime
   - umaPctLifetime
   - umaResourceLifetime
   - umaAddScopesAutomatically
   - umaValidateClaimToken
   - umaGrantAccessIfNoPolicies
   - umaRestrictResourceToAssociatedClient
   - umaKeepClientDuringResourceSetRegistration
   - umaRptAsJwt

**Comment by pujavs** [comment]
Implemented - /api/v1/oxauth/uma
{"umaAddScopesAutomatically":true,"umaConfigurationEndpoint":"https://pujavs2.infinity.com/oxauth/restv1/uma2-configuration","umaGrantAccessIfNoPolicies":false,"umaPctLifetime":2592000,"umaResourceLifetime":2592000,"umaRestrictResourceToAssociatedClient":false,"umaRptAsJwt":false,"umaRptLifetime":3600,"umaTicketLifetime":3600,"umaValidateClaimToken":false}

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/90086848-067dbf00-dd39-11ea-898b-72bb9e1a9bb9.png)
