### ISSUE TITLE
API Consumer updates an OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#91]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can update an existing OpenID client 
given it's inum.

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/clients/{inum}` where `{inum}` is the inum of an existing OpenID client
- The request must contain valid `API Consumer` authentication credentials
- The `API consumer` must have `write` permission to access the endpoint
- The request must contain a representation of an OpenID client
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a representation of the modified OpenID client

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89044766-53799280-d342-11ea-80d0-977b8aa79673.png)
