### ISSUE TITLE
API Consumer updates a non-existing OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#92]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that updates a non-existing OpenID client 
so that I can get an error describing why the operation failed

#### Acceptance Criteria 
- `API Consumer` sends a `PUT` request to `/api/v1/clients/{inum}` where `{inum}` is the inum of a non-existing OpenID client
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89027863-308bb600-d323-11ea-92e1-df39ec67ec72.png)

**Comment by syntrydy** [comment]
In case of missing attribute inum in the post body
![image](https://user-images.githubusercontent.com/7513418/89028224-d63f2500-d323-11ea-8c07-8eaeeb3e7b4b.png)
