### ISSUE TITLE
API Consumer partially updates an OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#93]
### User Story Meta Information
- Risk Level: 1
- **Priority: HIGH**
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can partially update an OpenID client

#### Acceptance Criteria 
- `API Consumer` sends a `PATCH` request to **`/api/v1/oxauth/openid/clients/{inum}`** where `{inum}` is the inum of an existing OpenID client
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- The request contains a partial representation of the OpenID client
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the modified OpenID client
#### Notes 
   No notes

**Comment by syntrydy** [comment]
@uprightech we need more details for the PATCH operation, we have to define which sub part of the entity customers will likely patch. For example, i see ClientAtrributes.
