### ISSUE TITLE
API Consumer deletes an OpenID client

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#95]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so that I can delete an existing OpenID client given
it's `inum`

#### Acceptance Criteria 
- `API Consumer` sends a `DELETE` request to `/api/v1/clients/{inum}` where `{inum}` is the inum of an existing OpenID client
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `write` permission to access the endpoint
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains the updated list of OpenID clients
#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89029010-5a45dc80-d325-11ea-89c8-9905386e19d2.png)
