### ISSUE TITLE
API Consumer fetches a single OpenID scope

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#98]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` so I can fetch a single OpenID scope
given it's `inum`

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/v1/oauth/scopes/{inum}` where `{inum}` is the inum 
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- `oxauth-config` returns a `200 OK` HTTP Response 
- The HTTP response body contains a single OpenID scope

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89196724-83bf6c00-d5a2-11ea-844f-496039c00833.png)
