### ISSUE TITLE
API Consumer fetches a non-existing OpenID scope

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxauth-config#99]
### User Story Meta Information
- Risk Level: 1
- Priority: 5
- Effort : N/A

### Description 
As an `API Consumer` ,  I want to send a request to `oxauth-config` that fetches a non-existing OpenID scope 
so that I can get an error message describing why the operation failed

#### Acceptance Criteria 
- `API Consumer` sends a `GET` request to `/v1/oauth/scopes/{inum}` where `{inum}` is the inum of 
   a non-existing OpenID scope
- The request must contain valid `API Consumer` authentication credentials 
- The `API consumer` must have `read` permission to access the endpoint
- `oxauth-config` returns a `404 Not Found` HTTP Response 
- The HTTP response body contains an error describing why the operation failed

#### Notes 
   No notes

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/89197251-57581f80-d5a3-11ea-942e-750ee6f42557.png)
